### ISSUE TITLE
Not using system theme

### ISSUE THREAD

**Issue by jepotter1-archive** [flathub/com.github.alainm23.planner#7]
### Summary

My system theme is Adwaita, but Planner looks like this:

![image](https://user-images.githubusercontent.com/20506149/108608297-f5160f00-737a-11eb-8b70-6b7660bd71b8.png)

Notice that the close button is on the left and there is a maximize button on the right, which is not consistent with GNOME's default window decoration scheme and reflects elementary's default window decorations. Other UI elements, like checkboxes, sliders, and buttons, are also using the elementary stylesheet.

There is an option to "use system window decoration" in the settings menu, but when I enable that option, it looks like this:

![image](https://user-images.githubusercontent.com/20506149/108608415-a026c880-737b-11eb-81b4-c91bca47c705.png)

Which is still not consistent with the newest version of Adwaita.

### Additional information

* The elementary GTK theme is not shown as installed in Flatpak, nor is it shown as a dependency of this application.
* No errors are shown upon starting the application.
* Other Flatpak apps correctly use Adwaita, including apps made for elementaryOS like ["Go For It"](https://github.com/flathub/de.manuel_kehl.go-for-it).

### Versions

* GNOME 3.38.4
* Fedora Silverblue 33.20210220.0
* Flatpak 1.10.1
* Planner 2.6.9

**Comment by alainm23** [comment]
We discussed a lot about this approach since the beginning of the project and we decided to enforce the elementary OS theme for many reasons.
The most obvious are:

- Ability to fully control the UI and UX of the application on every platform.
- Offer a consistent user experience to everyone.
- Remove the burden of supporting a million different DEs and Themes.
- Keep the focus on the architecture instead of spending time fixing themes issues.
